apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  namespace: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image:  "{{.Values.angular.image}}{{.Values.angular.tag}}"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular
  namespace: testing
spec:
  selector:
    app: angular
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
