apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: "{{.Values.django.image}}"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: testing
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
