apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: "{{ .Values.pgadmin.image }}:{{ .Values.pgadmin.tag }}"
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "root@root.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  type: NodePort
  ports:
  - port: 5050
    targetPort: 80
    nodePort: 30050
  selector:
    app: pgadmin

